### ISSUE TITLE
Update provider information

### ISSUE THREAD

**Issue by SerialVelocity** [rafalcieslak/emacs-company-terraform#4]
The provider information is pretty out of date now (for instance it doesn't have information about `aws_lb_listener` or `aws_lb_target_group`).

Ways of fixing it up that I can think of:
 - Use this as a submodule: https://github.com/juliosueiras/vim-terraform-completion/tree/master/provider_json
 - Use the generator that the vim plugin uses
 - Update/Run your script

**Comment by rafalcieslak** [comment]
Due to my mistake this update has only now reached Melpa - sorry for the delay.
